version: '3'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: location_marker
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:stable
    container_name: lm_webserver
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    working_dir: /var/www/html
    ports:
      - "8002:80"
      - "444:444"
    networks:
      - app-network
    volumes_from:
      - app

  # MySql Database
  mysql:
    image: mysql:latest
    container_name: lm_mysql
    restart: unless-stopped
    ports:
      - "4306:3306"
    env_file: ./src/.env
    volumes:
      - db-data:/var/lib/mysql/
    networks:
      - app-network

  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - '8003:80'
    env_file: ./src/.env
    environment:
      UPLOAD_LIMIT: 100M
    volumes:
      - db-data:/var/lib/mysql/
    networks:
      - app-network

networks:
  app-network:

    null
volumes:
  db-data:
    driver: local
